spring:

  application:
    name: bookstore-rest-api

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/cecko_bookstore_db
    username: cecko
    password: cecko